/*
Generated by Yara-Rules
On 12-04-2022
*/
include "./tests/Yara-Rules/rules/packers/JJencode.yar"
include "./tests/Yara-Rules/rules/packers/Javascript_exploit_and_obfuscation.yar"
include "./tests/Yara-Rules/rules/packers/packer.yar"
include "./tests/Yara-Rules/rules/packers/packer_compiler_signatures.yar"
include "./tests/Yara-Rules/rules/packers/peid.yar"
include "./tests/Yara-Rules/rules/packers/tweetable-polyglot-png.yar"
