/*
Generated by Yara-Rules
On 12-04-2022
*/
include "./tests/Yara-Rules/rules/webshells/WShell_APT_Laudanum.yar"
include "./tests/Yara-Rules/rules/webshells/WShell_ASPXSpy.yar"
include "./tests/Yara-Rules/rules/webshells/WShell_ChinaChopper.yar"
include "./tests/Yara-Rules/rules/webshells/WShell_Drupalgeddon2_icos.yar"
include "./tests/Yara-Rules/rules/webshells/WShell_PHP_Anuna.yar"
include "./tests/Yara-Rules/rules/webshells/WShell_PHP_in_images.yar"
include "./tests/Yara-Rules/rules/webshells/WShell_THOR_Webshells.yar"
include "./tests/Yara-Rules/rules/webshells/Wshell_ChineseSpam.yar"
include "./tests/Yara-Rules/rules/webshells/Wshell_fire2013.yar"
